apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: spark-job
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: spark-job 
            image: quay.io/eddie_esquivel/spark-master:2.2.0
            command:
            - "/bin/bash"
            - "-c"
            - "spark-submit --class org.apache.spark.examples.SparkPi  --master spark://spark-cluster-master:6066  --deploy-mode cluster  --supervise  --executor-memory 1G  --total-executor-cores 10  hdfs://hdfs-namenode:8020/demo/spark-examples_2.11-2.1.1.jar  100"
            volumeMounts:
            - mountPath: /opt/spark/conf
              name: conf
          restartPolicy: OnFailure
          volumes:
          - name: conf
            configMap:
              name: eddie-chart-conf
